standard js styling & formatting
natekchua/Spotifyre pull request #49
Opened 2020-12-22 08:54 UTC by awave1

2020-12-22 09:38 UTC, awave1 commented
@natekchua please review

2020-12-22 17:18 UTC, awave1 commented on package.json
> -    "postinstall": "npm-run-all --parallel install:*",
I converted the repo to support yarn workspaces so these scripts are no longer required. simply running `yarn install` or `yarn` in the project root will install dependencies in all workspaces `./client` and `./server`

2020-12-22 17:18 UTC, awave1 commented on package.json
> +    "clean": "rimraf node_modules/ server/node_modules client/node_modules "
running `yarn clean` or `npm run clean` will remove `node_modules` across workspaces. might be also useful to remove build folder(s) here too

2020-12-22 17:31 UTC, awave1 commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
this will enable autoformatting on save

2020-12-22 19:57 UTC, raksdewji commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
Should we just add this to the readme to de-clutter the folder

2020-12-22 19:58 UTC, raksdewji commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
Should we just add this to the readme to de-clutter the folder

2020-12-22 21:36 UTC, raksdewji commented on .husky/pre-commit
> +yarn lint
Instead of a .husky folder can this be added to package.json?
`"husky": {
    "hooks": {
      "pre-commit": "yarn lint"
    }
  },`

2020-12-22 21:39 UTC, awave1 commented on .husky/pre-commit
> +yarn lint
yea, just need to install v4 instead of latest version. they just changed how it's done in latest: https://typicode.github.io/husky/#/

2020-12-22 21:42 UTC, awave1 commented on .husky/pre-commit
> +yarn lint
you can run `yarn remove husky@next` (or just `yarn remove husky`) to remove it, and then just run `yarn add -DW husky`. run those commands in the root. then you should be able to add the config in `package.json`

2020-12-22 23:47 UTC, awave1 commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
wym?

2020-12-22 23:52 UTC, awave1 commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
i think it's ok to keep this `settings.json`, it'll just make it easier to setup project in future, but not opposed to just putting it in readme under project setup

2020-12-23 01:04 UTC, natekchua requested changes

2020-12-23 01:16 UTC, natekchua commented on .vscode/settings.json
> +        "source.fixAll.eslint": true
I think we should include it in the README instead. Gives us flexibility just in case someone doesn't want that autoformat on save (aka me LOL)

2020-12-23 03:36 UTC, raksdewji commented on client/package.json
> +  "proxy": "https://spotifyre-manager.netlify.app/",
3 am commits 💀, fixed.

2020-12-23 05:52 UTC, natekchua approved these changes

2020-12-23 23:38 UTC, raksdewji approved these changes

2020-12-23 23:38 UTC, raksdewji commented on client/package.json
> +    "dev": "cross-env NODE_ENV=development react-scripts start",
No longer need to change helperFunctions.js. Be sure to use `yarn dev` when running locally.

2020-12-23 23:38 UTC, raksdewji commented on server/package.json
> +    "dev": "cross-env NODE_ENV=development nodemon ./bin/www",
No longer need to change spotifyUtils.js. Be sure to use `yarn dev` when running locally.

2020-12-25 08:04 UTC, awave1 commented
🚀

2020-12-27 03:26 UTC, natekchua approved these changes

2020-12-27 03:38 UTC, merged