50/feat/add curator search
natekchua/Spotifyre pull request #53
Opened 2020-12-29 07:46 UTC by natekchua

pushing this PR while my PC is still alive lol

2021-01-08 02:29 UTC, raksdewji commented on client/src/components/PlaylistView/SongsResultsList/SongsResultsList.jsx
> +            <h3>Results found for &quot;{songsSearchQuery}&quot;. {songsFromQuery.items.length} songs returned.</h3>
``songsFromQuery?.items?.length``

2021-01-08 02:47 UTC, raksdewji approved these changes

2021-01-08 02:47 UTC, raksdewji commented on README.md
> +  <img alt="Version" src="https://img.shields.io/badge/version-1.1-blue.svg?cacheSeconds=2592000" />
![Alt Text](https://media.giphy.com/media/3o7abIileRivlGr8Nq/giphy.gif)

2021-01-08 06:44 UTC, awave1 requested changes

2021-01-08 06:44 UTC, awave1 commented on client/src/components/AppContainer/AppContainer.jsx
> +      {notification
can simplify to `{notification && ...}`

2021-01-08 06:44 UTC, awave1 commented on client/src/components/AppContainer/AppContainer.jsx
> +      {user
can simplify to `{user && ...}`

2021-01-08 06:44 UTC, awave1 commented on client/src/components/Notifications/NotificationRow.jsx
> +      <p>{notification?.suggested_by_username}&nbsp;suggested the song &quot;{notification?.song_title}&quot; to your playlist &quot;{notification?.playlist}&quot;.</p>
or you can just use template string and you wouldn't need to use escaped quotes:
```jsx
{`${notification?.suggested_by_username} suggested the song "${notification?.song_title}" to your playlist "${notification?.playlist}".`}
```

2021-01-08 06:44 UTC, awave1 commented on client/src/components/PlaylistView/CuratorShowcase/CuratorShowcase.tsx
> +    getCuratorPlaylists(params).then(res => {
since you already marked `goToCuratorProfile` as async, might as well use it:

```ts
const res = await getCuratorPlaylists(params);
setCuratorPlaylists(JSON.parse(res).curatorPlaylists);
// ...dispatches
```

2021-01-08 06:44 UTC, awave1 commented on server/src/actions/actions.js
> +    searchString !== 'undefined'
can just simplify to `searchString ? ... : ...`

2021-01-09 03:30 UTC, awave1 approved these changes

2021-01-09 03:45 UTC, merged